### ISSUE TITLE
Wrong order of the coordinates in API

### ISSUE THREAD

**Issue by PhilippCl** [Hator21/GeoGraph2017#41]
Openstreetmap:
     left is the longitude of the left (westernmost) side of the bounding box.
    bottom is the latitude of the bottom (southernmost) side of the bounding box.
    right is the longitude of the right (easternmost) side of the bounding box.
    top is the latitude of the top (northernmost) side of the bounding box.

http://www.overpass-api.de/api/xapi?map?bbox=8.8875961,52.284332,8.9294815,52.308898
NW lon: 8.8875961 NW lat: 52.308898 SE lon: 8.9294815 SE lat: 52.284332 Center lon: 8.908538799999999 Center lat: 52.296615

**Comment by Hator21** [comment]
Erledigt
