### ISSUE TITLE
[PARSER] Wrong displayed Map

### ISSUE THREAD

**Issue by Hator21** [Hator21/GeoGraph2017#80]
The displayed Nodes are not the same as the ones on Google Maps.

Maybe the Parser kicks to many Nodes out of the File.

**Comment by Hator21** [comment]
Cords we Used:[DEBUG] http://www.openstreetmap.org/api/0.6/map?bbox=6.17,50.8,6.18,50.81

**Comment by Hator21** [comment]
![anzeige](https://user-images.githubusercontent.com/16122050/27725253-c2949f70-5d75-11e7-8c93-d8ad7516c61a.PNG)

**Comment by ChristopherKL** [comment]
![unbenannt](https://user-images.githubusercontent.com/27887612/27725243-b4cf65c8-5d75-11e7-9c02-f04a56311108.PNG)

**Comment by StefanSchuck** [comment]
The Relations are Crap, OSM is a half done Project, so the streets that werent't parsed were the one not considered in the Relations which describe a Highway. I altered the algorithm accordingly and now i get a lot more ways, perhaps too much, but that needs to be confirmed first. Please look for yourselfes and verify this as Done. If there are still Streets not considered by the parser, send me the OSM File.
